import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isFetched } = api.example.hello.useQuery({
    text: "Hello World!",
  });
  const { user } = useUser();

  if (data) {
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignInButton />
        <UserButton
          appearance={{
            // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
            baseTheme: dark,
          }}
        />
      </main>
    </>
  );
};

export default Home;
