import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { mutate } = api.wallet.add.useMutation();
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>DefiSight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user && <SignInButton />}
        {user && (
          <UserButton
            appearance={{
              // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
              baseTheme: dark,
            }}
          />
        )}
        <form
          className="flex flex-col"
          onSubmit={(e) => {
            e.preventDefault();
            console.log(e.target.address.value);
          }}
        >
          <div className="m-1">
            <input type="text" id="address" minLength={10} />
          </div>
          <div className="m-1">
            <input type="text" id="chainId" />
          </div>
          <div className="m-1">
            <input type="text" id="tag" />
          </div>
          <div className="m-1">
            <input type="text" id="highlight" />
          </div>
          <div className="m-1">
            <button type="submit">Submit</button>
          </div>
        </form>
      </main>
    </>
  );
};

export default Home;
